#first stage - builder
FROM gravitl/go-builder as builder

ARG version 

WORKDIR /app

COPY . .

WORKDIR /app/turnserver
ENV GO111MODULE=auto

RUN GOOS=linux CGO_ENABLED=1 go build -ldflags="-s -X 'main.version=${version}'" -o turnserver main.go
FROM alpine:3.15.2

# set the working directory
WORKDIR /root/

COPY --from=builder /app/turnserver/turnserver .

ENTRYPOINT ["./turnserver"]