#first stage - builder
FROM golang:1.17
ARG version
WORKDIR /app
COPY . .
ENV GO111MODULE=auto

# RUN GOOS=linux CGO_ENABLED=1 go build -tags debug -ldflags="-s -X 'main.version=$version'" -o netmaker main.go
RUN GOOS=linux CGO_ENABLED=1 go build -ldflags="-s -X 'main.version=$version'" -o netmaker main.go