apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmaker-grpc
  labels:
    app: netmaker-grpc
spec:
  selector:
    matchLabels:
      app: netmaker-grpc
  replicas: 1
  template:
    metadata:
      labels:
        app: netmaker-grpc
    spec:
      containers:
      - name: netmaker-grpc
        image: gravitl/netmaker:v0.5.7
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nm-pvc
          mountPath: /root/dnsconfig
        env:
        - name: SERVER_API_CONN_STRING
          value: "api.nm.k8s.gravitl.com:443"
        - name: SERVER_GRPC_CONN_STRING
          value: "grpc.nm.k8s.gravitl.com:443"
        - name: COREDNS_ADDR
          value: "netmaker-dns"
        - name: GRPC_SSL
          value: "on"
        - name: CLIENT_MODE
          value: "off"
        - name: DNS_MODE
          value: "on"
        - name: MASTER_KEY
          value: "Unkn0wn!"
        - name: SERVER_GRPC_WIREGUARD
          value: "off"
        - name: MASTER_KEY
          value: "secretkey"
        - name: CORS_ALLOWED_ORIGIN
          value: "*"
        - name: DISABLE_REMOTE_IP_CHECK
          value: "on"
        - name: MONGO_ADMIN
          value: "mongoadmin"
        - name: MONGO_PASS
          value: "mongopass"
        - name: MONGO_HOST
          value: "mongo-0.mongo"
        - name: MONGO_OPTS
          value: "/?authSource=admin"
        - name: SERVER_GRPC_HOST
          value: "0.0.0.0"
        - name: GRPC_PORT
          value: "443"
        - name: REST_BACKEND
          value: "off"
      volumes:
      - name: nm-pvc
        persistentVolumeClaim:
          claimName: nm-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netmaker-grpc
  name: netmaker-grpc
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: netmaker-grpc
  sessionAffinity: None
  type: ClusterIP

