apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netclient-1
  labels:
    app: netclient-1
spec:
  selector:
    matchLabels:
      app: netclient-1
  template:
    metadata:
      labels:
        app: netclient-1
    spec:
      hostNetwork: true
      containers:
      - name: netclient-1
        image: gravitl/netclient:0.9.2-doks-uspace
        env:
        - name: NETCLIENT_ROAMING
          value: "no"
        - name: NETCLIENT_PORT
          value: "51821"
        - name: NETCLIENT_IS_STATIC
          value: "yes"
        - name: NETCLIENT_ENDPOINT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: TOKEN
          value: "<token>"
        volumeMounts:
        - mountPath: /etc/netclient
          name: etc-netclient
        securityContext:
          privileged: true
      volumes:
      - hostPath:
          path: /etc/netclient
          type: DirectoryOrCreate
        name: etc-netclient

