name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["ok-john", "0xdcarns", "afeiszli",  "mattkasun"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you running?
      options:
        - v0.15.1      
        - v0.15.0
        - v0.14.6
        - v0.14.5
        - v0.14.4
        - v0.14.3      
        - v0.14.2
        - v0.14.1
        - v0.14.0      
        - v0.13.1
        - v0.13.0
        - v0.12.2
        - v0.12.1
        - v0.12.0
        - v0.11.1
        - v0.11.0
        - v0.10.0
        - v0.9.4
        - v0.9.3
        - v0.9.2
        - v0.9.1
        - v0.9.0
        - v0.8.5
        - Not sure
        - Not listed
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you using?
      multiple: true
      options:
        - Linux
        - FreeBSD
        - Windows
        - Mac
        - Unlisted
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Contributing guidelines
      description: Have you read [CONTRIBUTING.md](https://github.com/gravitl/netmaker/blob/master/CONTRIBUTING.md)
      options:
        - label: Yes, I did.
          required: true
