ARG NM_VERSION=

FROM gravitl/builder as builder

RUN apk add --update git build-base libmnl-dev iptables

WORKDIR /root/
RUN git clone https://git.zx2c4.com/wireguard-go && \
    cd wireguard-go && \
    make && \
    make install

FROM gravitl/netmaker:${NM_VERSION}

RUN apk add --no-cache --update libmnl iptables openresolv iproute2
COPY --from=builder /usr/bin/wireguard-go /usr/bin/wg* /usr/bin/
