FROM alpine:3.13.6

RUN apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl go 

RUN wget -O go.tgz https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz 

RUN tar -C /usr/local -xzf go.tgz 

WORKDIR /usr/local/go/src

RUN chmod +x make.bash

RUN ./make.bash 

ENV PATH="/usr/local/go/bin:$PATH"

ENV GOPATH=/opt/go/ 

ENV PATH=$PATH:$GOPATH/bin 

RUN apk del .build-deps

RUN apk add build-base
