// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/node.proto

package nodepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Macaddress           string   `protobuf:"bytes,1,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Network              string   `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMacaddress() string {
	if m != nil {
		return m.Macaddress
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type LoginResponse struct {
	Accesstoken          string   `protobuf:"bytes,1,opt,name=accesstoken,proto3" json:"accesstoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAccesstoken() string {
	if m != nil {
		return m.Accesstoken
	}
	return ""
}

type Node struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Address6             string   `protobuf:"bytes,26,opt,name=address6,proto3" json:"address6,omitempty"`
	Listenport           int32    `protobuf:"varint,4,opt,name=listenport,proto3" json:"listenport,omitempty"`
	Publickey            string   `protobuf:"bytes,5,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Endpoint             string   `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Macaddress           string   `protobuf:"bytes,7,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Nodenetwork          string   `protobuf:"bytes,9,opt,name=nodenetwork,proto3" json:"nodenetwork,omitempty"`
	Ispending            bool     `protobuf:"varint,10,opt,name=ispending,proto3" json:"ispending,omitempty"`
	Postup               string   `protobuf:"bytes,11,opt,name=postup,proto3" json:"postup,omitempty"`
	Postdown             string   `protobuf:"bytes,12,opt,name=postdown,proto3" json:"postdown,omitempty"`
	Keepalive            int32    `protobuf:"varint,13,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	Saveconfig           bool     `protobuf:"varint,14,opt,name=saveconfig,proto3" json:"saveconfig,omitempty"`
	Accesskey            string   `protobuf:"bytes,15,opt,name=accesskey,proto3" json:"accesskey,omitempty"`
	Interface            string   `protobuf:"bytes,16,opt,name=interface,proto3" json:"interface,omitempty"`
	Lastcheckin          string   `protobuf:"bytes,17,opt,name=lastcheckin,proto3" json:"lastcheckin,omitempty"`
	Lastmodified         string   `protobuf:"bytes,18,opt,name=lastmodified,proto3" json:"lastmodified,omitempty"`
	Checkininterval      int32    `protobuf:"varint,19,opt,name=checkininterval,proto3" json:"checkininterval,omitempty"`
	Localaddress         string   `protobuf:"bytes,20,opt,name=localaddress,proto3" json:"localaddress,omitempty"`
	Postchanges          string   `protobuf:"bytes,21,opt,name=postchanges,proto3" json:"postchanges,omitempty"`
	Allowedips           string   `protobuf:"bytes,22,opt,name=allowedips,proto3" json:"allowedips,omitempty"`
	Islocal              bool     `protobuf:"varint,23,opt,name=islocal,proto3" json:"islocal,omitempty"`
	Isingressgateway     bool     `protobuf:"varint,28,opt,name=isingressgateway,proto3" json:"isingressgateway,omitempty"`
	Isdualstack          bool     `protobuf:"varint,27,opt,name=isdualstack,proto3" json:"isdualstack,omitempty"`
	Dnsoff               bool     `protobuf:"varint,24,opt,name=dnsoff,proto3" json:"dnsoff,omitempty"`
	Localrange           string   `protobuf:"bytes,25,opt,name=localrange,proto3" json:"localrange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{2}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetAddress6() string {
	if m != nil {
		return m.Address6
	}
	return ""
}

func (m *Node) GetListenport() int32 {
	if m != nil {
		return m.Listenport
	}
	return 0
}

func (m *Node) GetPublickey() string {
	if m != nil {
		return m.Publickey
	}
	return ""
}

func (m *Node) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Node) GetMacaddress() string {
	if m != nil {
		return m.Macaddress
	}
	return ""
}

func (m *Node) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Node) GetNodenetwork() string {
	if m != nil {
		return m.Nodenetwork
	}
	return ""
}

func (m *Node) GetIspending() bool {
	if m != nil {
		return m.Ispending
	}
	return false
}

func (m *Node) GetPostup() string {
	if m != nil {
		return m.Postup
	}
	return ""
}

func (m *Node) GetPostdown() string {
	if m != nil {
		return m.Postdown
	}
	return ""
}

func (m *Node) GetKeepalive() int32 {
	if m != nil {
		return m.Keepalive
	}
	return 0
}

func (m *Node) GetSaveconfig() bool {
	if m != nil {
		return m.Saveconfig
	}
	return false
}

func (m *Node) GetAccesskey() string {
	if m != nil {
		return m.Accesskey
	}
	return ""
}

func (m *Node) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *Node) GetLastcheckin() string {
	if m != nil {
		return m.Lastcheckin
	}
	return ""
}

func (m *Node) GetLastmodified() string {
	if m != nil {
		return m.Lastmodified
	}
	return ""
}

func (m *Node) GetCheckininterval() int32 {
	if m != nil {
		return m.Checkininterval
	}
	return 0
}

func (m *Node) GetLocaladdress() string {
	if m != nil {
		return m.Localaddress
	}
	return ""
}

func (m *Node) GetPostchanges() string {
	if m != nil {
		return m.Postchanges
	}
	return ""
}

func (m *Node) GetAllowedips() string {
	if m != nil {
		return m.Allowedips
	}
	return ""
}

func (m *Node) GetIslocal() bool {
	if m != nil {
		return m.Islocal
	}
	return false
}

func (m *Node) GetIsingressgateway() bool {
	if m != nil {
		return m.Isingressgateway
	}
	return false
}

func (m *Node) GetIsdualstack() bool {
	if m != nil {
		return m.Isdualstack
	}
	return false
}

func (m *Node) GetDnsoff() bool {
	if m != nil {
		return m.Dnsoff
	}
	return false
}

func (m *Node) GetLocalrange() string {
	if m != nil {
		return m.Localrange
	}
	return ""
}

type CheckInResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Needpeerupdate       bool     `protobuf:"varint,2,opt,name=needpeerupdate,proto3" json:"needpeerupdate,omitempty"`
	Needconfigupdate     bool     `protobuf:"varint,3,opt,name=needconfigupdate,proto3" json:"needconfigupdate,omitempty"`
	Nodemessage          string   `protobuf:"bytes,4,opt,name=nodemessage,proto3" json:"nodemessage,omitempty"`
	Ispending            bool     `protobuf:"varint,5,opt,name=ispending,proto3" json:"ispending,omitempty"`
	Needkeyupdate        bool     `protobuf:"varint,6,opt,name=needkeyupdate,proto3" json:"needkeyupdate,omitempty"`
	Needdelete           bool     `protobuf:"varint,7,opt,name=needdelete,proto3" json:"needdelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckInResponse) Reset()         { *m = CheckInResponse{} }
func (m *CheckInResponse) String() string { return proto.CompactTextString(m) }
func (*CheckInResponse) ProtoMessage()    {}
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{3}
}

func (m *CheckInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInResponse.Unmarshal(m, b)
}
func (m *CheckInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInResponse.Marshal(b, m, deterministic)
}
func (m *CheckInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInResponse.Merge(m, src)
}
func (m *CheckInResponse) XXX_Size() int {
	return xxx_messageInfo_CheckInResponse.Size(m)
}
func (m *CheckInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInResponse proto.InternalMessageInfo

func (m *CheckInResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CheckInResponse) GetNeedpeerupdate() bool {
	if m != nil {
		return m.Needpeerupdate
	}
	return false
}

func (m *CheckInResponse) GetNeedconfigupdate() bool {
	if m != nil {
		return m.Needconfigupdate
	}
	return false
}

func (m *CheckInResponse) GetNodemessage() string {
	if m != nil {
		return m.Nodemessage
	}
	return ""
}

func (m *CheckInResponse) GetIspending() bool {
	if m != nil {
		return m.Ispending
	}
	return false
}

func (m *CheckInResponse) GetNeedkeyupdate() bool {
	if m != nil {
		return m.Needkeyupdate
	}
	return false
}

func (m *CheckInResponse) GetNeeddelete() bool {
	if m != nil {
		return m.Needdelete
	}
	return false
}

type PeersResponse struct {
	Isegressgateway      bool     `protobuf:"varint,1,opt,name=isegressgateway,proto3" json:"isegressgateway,omitempty"`
	Egressgatewayrange   string   `protobuf:"bytes,2,opt,name=egressgatewayrange,proto3" json:"egressgatewayrange,omitempty"`
	Publickey            string   `protobuf:"bytes,5,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Endpoint             string   `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Address6             string   `protobuf:"bytes,8,opt,name=address6,proto3" json:"address6,omitempty"`
	Listenport           int32    `protobuf:"varint,4,opt,name=listenport,proto3" json:"listenport,omitempty"`
	Localaddress         string   `protobuf:"bytes,7,opt,name=localaddress,proto3" json:"localaddress,omitempty"`
	Keepalive            int32    `protobuf:"varint,13,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersResponse) Reset()         { *m = PeersResponse{} }
func (m *PeersResponse) String() string { return proto.CompactTextString(m) }
func (*PeersResponse) ProtoMessage()    {}
func (*PeersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{4}
}

func (m *PeersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersResponse.Unmarshal(m, b)
}
func (m *PeersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersResponse.Marshal(b, m, deterministic)
}
func (m *PeersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersResponse.Merge(m, src)
}
func (m *PeersResponse) XXX_Size() int {
	return xxx_messageInfo_PeersResponse.Size(m)
}
func (m *PeersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeersResponse proto.InternalMessageInfo

func (m *PeersResponse) GetIsegressgateway() bool {
	if m != nil {
		return m.Isegressgateway
	}
	return false
}

func (m *PeersResponse) GetEgressgatewayrange() string {
	if m != nil {
		return m.Egressgatewayrange
	}
	return ""
}

func (m *PeersResponse) GetPublickey() string {
	if m != nil {
		return m.Publickey
	}
	return ""
}

func (m *PeersResponse) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *PeersResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PeersResponse) GetAddress6() string {
	if m != nil {
		return m.Address6
	}
	return ""
}

func (m *PeersResponse) GetListenport() int32 {
	if m != nil {
		return m.Listenport
	}
	return 0
}

func (m *PeersResponse) GetLocaladdress() string {
	if m != nil {
		return m.Localaddress
	}
	return ""
}

func (m *PeersResponse) GetKeepalive() int32 {
	if m != nil {
		return m.Keepalive
	}
	return 0
}

type ExtPeersResponse struct {
	Publickey            string   `protobuf:"bytes,5,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Endpoint             string   `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Address6             string   `protobuf:"bytes,8,opt,name=address6,proto3" json:"address6,omitempty"`
	Listenport           int32    `protobuf:"varint,4,opt,name=listenport,proto3" json:"listenport,omitempty"`
	Localaddress         string   `protobuf:"bytes,7,opt,name=localaddress,proto3" json:"localaddress,omitempty"`
	Keepalive            int32    `protobuf:"varint,13,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExtPeersResponse) Reset()         { *m = ExtPeersResponse{} }
func (m *ExtPeersResponse) String() string { return proto.CompactTextString(m) }
func (*ExtPeersResponse) ProtoMessage()    {}
func (*ExtPeersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{5}
}

func (m *ExtPeersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExtPeersResponse.Unmarshal(m, b)
}
func (m *ExtPeersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExtPeersResponse.Marshal(b, m, deterministic)
}
func (m *ExtPeersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExtPeersResponse.Merge(m, src)
}
func (m *ExtPeersResponse) XXX_Size() int {
	return xxx_messageInfo_ExtPeersResponse.Size(m)
}
func (m *ExtPeersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExtPeersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExtPeersResponse proto.InternalMessageInfo

func (m *ExtPeersResponse) GetPublickey() string {
	if m != nil {
		return m.Publickey
	}
	return ""
}

func (m *ExtPeersResponse) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ExtPeersResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ExtPeersResponse) GetAddress6() string {
	if m != nil {
		return m.Address6
	}
	return ""
}

func (m *ExtPeersResponse) GetListenport() int32 {
	if m != nil {
		return m.Listenport
	}
	return 0
}

func (m *ExtPeersResponse) GetLocaladdress() string {
	if m != nil {
		return m.Localaddress
	}
	return ""
}

func (m *ExtPeersResponse) GetKeepalive() int32 {
	if m != nil {
		return m.Keepalive
	}
	return 0
}

type Client struct {
	Privatekey           string   `protobuf:"bytes,1,opt,name=privatekey,proto3" json:"privatekey,omitempty"`
	Publickey            string   `protobuf:"bytes,2,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Accesskey            string   `protobuf:"bytes,3,opt,name=accesskey,proto3" json:"accesskey,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Address6             string   `protobuf:"bytes,5,opt,name=address6,proto3" json:"address6,omitempty"`
	Serverendpoint       string   `protobuf:"bytes,6,opt,name=serverendpoint,proto3" json:"serverendpoint,omitempty"`
	Serverport           string   `protobuf:"bytes,7,opt,name=serverport,proto3" json:"serverport,omitempty"`
	Serverkey            string   `protobuf:"bytes,8,opt,name=serverkey,proto3" json:"serverkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{6}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetPrivatekey() string {
	if m != nil {
		return m.Privatekey
	}
	return ""
}

func (m *Client) GetPublickey() string {
	if m != nil {
		return m.Publickey
	}
	return ""
}

func (m *Client) GetAccesskey() string {
	if m != nil {
		return m.Accesskey
	}
	return ""
}

func (m *Client) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Client) GetAddress6() string {
	if m != nil {
		return m.Address6
	}
	return ""
}

func (m *Client) GetServerendpoint() string {
	if m != nil {
		return m.Serverendpoint
	}
	return ""
}

func (m *Client) GetServerport() string {
	if m != nil {
		return m.Serverport
	}
	return ""
}

func (m *Client) GetServerkey() string {
	if m != nil {
		return m.Serverkey
	}
	return ""
}

type CreateNodeReq struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNodeReq) Reset()         { *m = CreateNodeReq{} }
func (m *CreateNodeReq) String() string { return proto.CompactTextString(m) }
func (*CreateNodeReq) ProtoMessage()    {}
func (*CreateNodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{7}
}

func (m *CreateNodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNodeReq.Unmarshal(m, b)
}
func (m *CreateNodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNodeReq.Marshal(b, m, deterministic)
}
func (m *CreateNodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNodeReq.Merge(m, src)
}
func (m *CreateNodeReq) XXX_Size() int {
	return xxx_messageInfo_CreateNodeReq.Size(m)
}
func (m *CreateNodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNodeReq proto.InternalMessageInfo

func (m *CreateNodeReq) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type CreateNodeRes struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNodeRes) Reset()         { *m = CreateNodeRes{} }
func (m *CreateNodeRes) String() string { return proto.CompactTextString(m) }
func (*CreateNodeRes) ProtoMessage()    {}
func (*CreateNodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{8}
}

func (m *CreateNodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNodeRes.Unmarshal(m, b)
}
func (m *CreateNodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNodeRes.Marshal(b, m, deterministic)
}
func (m *CreateNodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNodeRes.Merge(m, src)
}
func (m *CreateNodeRes) XXX_Size() int {
	return xxx_messageInfo_CreateNodeRes.Size(m)
}
func (m *CreateNodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNodeRes proto.InternalMessageInfo

func (m *CreateNodeRes) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type UpdateNodeReq struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeReq) Reset()         { *m = UpdateNodeReq{} }
func (m *UpdateNodeReq) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeReq) ProtoMessage()    {}
func (*UpdateNodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{9}
}

func (m *UpdateNodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeReq.Unmarshal(m, b)
}
func (m *UpdateNodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeReq.Marshal(b, m, deterministic)
}
func (m *UpdateNodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeReq.Merge(m, src)
}
func (m *UpdateNodeReq) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeReq.Size(m)
}
func (m *UpdateNodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeReq proto.InternalMessageInfo

func (m *UpdateNodeReq) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type UpdateNodeRes struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeRes) Reset()         { *m = UpdateNodeRes{} }
func (m *UpdateNodeRes) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeRes) ProtoMessage()    {}
func (*UpdateNodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{10}
}

func (m *UpdateNodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeRes.Unmarshal(m, b)
}
func (m *UpdateNodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeRes.Marshal(b, m, deterministic)
}
func (m *UpdateNodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeRes.Merge(m, src)
}
func (m *UpdateNodeRes) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeRes.Size(m)
}
func (m *UpdateNodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeRes proto.InternalMessageInfo

func (m *UpdateNodeRes) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type ReadNodeReq struct {
	Macaddress           string   `protobuf:"bytes,1,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNodeReq) Reset()         { *m = ReadNodeReq{} }
func (m *ReadNodeReq) String() string { return proto.CompactTextString(m) }
func (*ReadNodeReq) ProtoMessage()    {}
func (*ReadNodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{11}
}

func (m *ReadNodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNodeReq.Unmarshal(m, b)
}
func (m *ReadNodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNodeReq.Marshal(b, m, deterministic)
}
func (m *ReadNodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNodeReq.Merge(m, src)
}
func (m *ReadNodeReq) XXX_Size() int {
	return xxx_messageInfo_ReadNodeReq.Size(m)
}
func (m *ReadNodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNodeReq proto.InternalMessageInfo

func (m *ReadNodeReq) GetMacaddress() string {
	if m != nil {
		return m.Macaddress
	}
	return ""
}

func (m *ReadNodeReq) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type ReadNodeRes struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNodeRes) Reset()         { *m = ReadNodeRes{} }
func (m *ReadNodeRes) String() string { return proto.CompactTextString(m) }
func (*ReadNodeRes) ProtoMessage()    {}
func (*ReadNodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{12}
}

func (m *ReadNodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNodeRes.Unmarshal(m, b)
}
func (m *ReadNodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNodeRes.Marshal(b, m, deterministic)
}
func (m *ReadNodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNodeRes.Merge(m, src)
}
func (m *ReadNodeRes) XXX_Size() int {
	return xxx_messageInfo_ReadNodeRes.Size(m)
}
func (m *ReadNodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNodeRes proto.InternalMessageInfo

func (m *ReadNodeRes) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type DeleteNodeReq struct {
	Macaddress           string   `protobuf:"bytes,1,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	NetworkName          string   `protobuf:"bytes,2,opt,name=networkName,proto3" json:"networkName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNodeReq) Reset()         { *m = DeleteNodeReq{} }
func (m *DeleteNodeReq) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeReq) ProtoMessage()    {}
func (*DeleteNodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{13}
}

func (m *DeleteNodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeReq.Unmarshal(m, b)
}
func (m *DeleteNodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeReq.Marshal(b, m, deterministic)
}
func (m *DeleteNodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeReq.Merge(m, src)
}
func (m *DeleteNodeReq) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeReq.Size(m)
}
func (m *DeleteNodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeReq proto.InternalMessageInfo

func (m *DeleteNodeReq) GetMacaddress() string {
	if m != nil {
		return m.Macaddress
	}
	return ""
}

func (m *DeleteNodeReq) GetNetworkName() string {
	if m != nil {
		return m.NetworkName
	}
	return ""
}

type DeleteNodeRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNodeRes) Reset()         { *m = DeleteNodeRes{} }
func (m *DeleteNodeRes) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeRes) ProtoMessage()    {}
func (*DeleteNodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{14}
}

func (m *DeleteNodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeRes.Unmarshal(m, b)
}
func (m *DeleteNodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeRes.Marshal(b, m, deterministic)
}
func (m *DeleteNodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeRes.Merge(m, src)
}
func (m *DeleteNodeRes) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeRes.Size(m)
}
func (m *DeleteNodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeRes proto.InternalMessageInfo

func (m *DeleteNodeRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetPeersReq struct {
	Macaddress           string   `protobuf:"bytes,1,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeersReq) Reset()         { *m = GetPeersReq{} }
func (m *GetPeersReq) String() string { return proto.CompactTextString(m) }
func (*GetPeersReq) ProtoMessage()    {}
func (*GetPeersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{15}
}

func (m *GetPeersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeersReq.Unmarshal(m, b)
}
func (m *GetPeersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeersReq.Marshal(b, m, deterministic)
}
func (m *GetPeersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeersReq.Merge(m, src)
}
func (m *GetPeersReq) XXX_Size() int {
	return xxx_messageInfo_GetPeersReq.Size(m)
}
func (m *GetPeersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeersReq proto.InternalMessageInfo

func (m *GetPeersReq) GetMacaddress() string {
	if m != nil {
		return m.Macaddress
	}
	return ""
}

func (m *GetPeersReq) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type GetExtPeersReq struct {
	Macaddress           string   `protobuf:"bytes,1,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExtPeersReq) Reset()         { *m = GetExtPeersReq{} }
func (m *GetExtPeersReq) String() string { return proto.CompactTextString(m) }
func (*GetExtPeersReq) ProtoMessage()    {}
func (*GetExtPeersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{16}
}

func (m *GetExtPeersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExtPeersReq.Unmarshal(m, b)
}
func (m *GetExtPeersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExtPeersReq.Marshal(b, m, deterministic)
}
func (m *GetExtPeersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExtPeersReq.Merge(m, src)
}
func (m *GetExtPeersReq) XXX_Size() int {
	return xxx_messageInfo_GetExtPeersReq.Size(m)
}
func (m *GetExtPeersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExtPeersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetExtPeersReq proto.InternalMessageInfo

func (m *GetExtPeersReq) GetMacaddress() string {
	if m != nil {
		return m.Macaddress
	}
	return ""
}

func (m *GetExtPeersReq) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type GetPeersRes struct {
	Peers                *PeersResponse `protobuf:"bytes,1,opt,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPeersRes) Reset()         { *m = GetPeersRes{} }
func (m *GetPeersRes) String() string { return proto.CompactTextString(m) }
func (*GetPeersRes) ProtoMessage()    {}
func (*GetPeersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{17}
}

func (m *GetPeersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeersRes.Unmarshal(m, b)
}
func (m *GetPeersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeersRes.Marshal(b, m, deterministic)
}
func (m *GetPeersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeersRes.Merge(m, src)
}
func (m *GetPeersRes) XXX_Size() int {
	return xxx_messageInfo_GetPeersRes.Size(m)
}
func (m *GetPeersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeersRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeersRes proto.InternalMessageInfo

func (m *GetPeersRes) GetPeers() *PeersResponse {
	if m != nil {
		return m.Peers
	}
	return nil
}

type GetExtPeersRes struct {
	Extpeers             *ExtPeersResponse `protobuf:"bytes,1,opt,name=extpeers,proto3" json:"extpeers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetExtPeersRes) Reset()         { *m = GetExtPeersRes{} }
func (m *GetExtPeersRes) String() string { return proto.CompactTextString(m) }
func (*GetExtPeersRes) ProtoMessage()    {}
func (*GetExtPeersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{18}
}

func (m *GetExtPeersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExtPeersRes.Unmarshal(m, b)
}
func (m *GetExtPeersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExtPeersRes.Marshal(b, m, deterministic)
}
func (m *GetExtPeersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExtPeersRes.Merge(m, src)
}
func (m *GetExtPeersRes) XXX_Size() int {
	return xxx_messageInfo_GetExtPeersRes.Size(m)
}
func (m *GetExtPeersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExtPeersRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetExtPeersRes proto.InternalMessageInfo

func (m *GetExtPeersRes) GetExtpeers() *ExtPeersResponse {
	if m != nil {
		return m.Extpeers
	}
	return nil
}

type CheckInReq struct {
	Node                 *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckInReq) Reset()         { *m = CheckInReq{} }
func (m *CheckInReq) String() string { return proto.CompactTextString(m) }
func (*CheckInReq) ProtoMessage()    {}
func (*CheckInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{19}
}

func (m *CheckInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInReq.Unmarshal(m, b)
}
func (m *CheckInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInReq.Marshal(b, m, deterministic)
}
func (m *CheckInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInReq.Merge(m, src)
}
func (m *CheckInReq) XXX_Size() int {
	return xxx_messageInfo_CheckInReq.Size(m)
}
func (m *CheckInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInReq proto.InternalMessageInfo

func (m *CheckInReq) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type CheckInRes struct {
	Checkinresponse      *CheckInResponse `protobuf:"bytes,1,opt,name=checkinresponse,proto3" json:"checkinresponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CheckInRes) Reset()         { *m = CheckInRes{} }
func (m *CheckInRes) String() string { return proto.CompactTextString(m) }
func (*CheckInRes) ProtoMessage()    {}
func (*CheckInRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13bd996b67da4ef, []int{20}
}

func (m *CheckInRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInRes.Unmarshal(m, b)
}
func (m *CheckInRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInRes.Marshal(b, m, deterministic)
}
func (m *CheckInRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInRes.Merge(m, src)
}
func (m *CheckInRes) XXX_Size() int {
	return xxx_messageInfo_CheckInRes.Size(m)
}
func (m *CheckInRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInRes.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInRes proto.InternalMessageInfo

func (m *CheckInRes) GetCheckinresponse() *CheckInResponse {
	if m != nil {
		return m.Checkinresponse
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "node.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "node.LoginResponse")
	proto.RegisterType((*Node)(nil), "node.Node")
	proto.RegisterType((*CheckInResponse)(nil), "node.CheckInResponse")
	proto.RegisterType((*PeersResponse)(nil), "node.PeersResponse")
	proto.RegisterType((*ExtPeersResponse)(nil), "node.ExtPeersResponse")
	proto.RegisterType((*Client)(nil), "node.Client")
	proto.RegisterType((*CreateNodeReq)(nil), "node.CreateNodeReq")
	proto.RegisterType((*CreateNodeRes)(nil), "node.CreateNodeRes")
	proto.RegisterType((*UpdateNodeReq)(nil), "node.UpdateNodeReq")
	proto.RegisterType((*UpdateNodeRes)(nil), "node.UpdateNodeRes")
	proto.RegisterType((*ReadNodeReq)(nil), "node.ReadNodeReq")
	proto.RegisterType((*ReadNodeRes)(nil), "node.ReadNodeRes")
	proto.RegisterType((*DeleteNodeReq)(nil), "node.DeleteNodeReq")
	proto.RegisterType((*DeleteNodeRes)(nil), "node.DeleteNodeRes")
	proto.RegisterType((*GetPeersReq)(nil), "node.GetPeersReq")
	proto.RegisterType((*GetExtPeersReq)(nil), "node.GetExtPeersReq")
	proto.RegisterType((*GetPeersRes)(nil), "node.GetPeersRes")
	proto.RegisterType((*GetExtPeersRes)(nil), "node.GetExtPeersRes")
	proto.RegisterType((*CheckInReq)(nil), "node.CheckInReq")
	proto.RegisterType((*CheckInRes)(nil), "node.CheckInRes")
}

func init() { proto.RegisterFile("grpc/node.proto", fileDescriptor_d13bd996b67da4ef) }

var fileDescriptor_d13bd996b67da4ef = []byte{
	// 1093 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0x96, 0x9d, 0xd8, 0x71, 0x5f, 0xd7, 0x49, 0x3a, 0x6d, 0xc3, 0x60, 0xaa, 0x2a, 0x5a, 0xa1,
	0x2a, 0x45, 0x24, 0x0e, 0x41, 0xaa, 0x90, 0x38, 0x20, 0x91, 0xa2, 0x08, 0x04, 0x15, 0x2c, 0xe2,
	0xc2, 0x6d, 0xb2, 0xfb, 0x7a, 0x3b, 0xf2, 0x66, 0x66, 0xb3, 0x33, 0xb6, 0x9b, 0x1b, 0x17, 0x7e,
	0x14, 0xe2, 0x9f, 0x70, 0xe6, 0x87, 0xa0, 0xf9, 0x58, 0xef, 0xec, 0xc6, 0x4d, 0x52, 0xe5, 0xc6,
	0xcd, 0xf3, 0xcc, 0xfb, 0xf9, 0xbc, 0x1f, 0x3b, 0x86, 0x9d, 0xac, 0x2c, 0x92, 0x89, 0x90, 0x29,
	0x1e, 0x15, 0xa5, 0xd4, 0x92, 0x6c, 0x9a, 0xdf, 0x51, 0x0a, 0x0f, 0x7f, 0x94, 0x19, 0x17, 0x31,
	0x5e, 0xce, 0x51, 0x69, 0xf2, 0x1c, 0xe0, 0x82, 0x25, 0x2c, 0x4d, 0x4b, 0x54, 0x8a, 0x76, 0xf6,
	0x3b, 0x07, 0x0f, 0xe2, 0x00, 0x21, 0x63, 0x18, 0x14, 0x4c, 0xa9, 0xa5, 0x2c, 0x53, 0xda, 0xb5,
	0xb7, 0xab, 0x33, 0xa1, 0xb0, 0x25, 0x50, 0x2f, 0x65, 0x39, 0xa3, 0x1b, 0xf6, 0xaa, 0x3a, 0x46,
	0x5f, 0xc0, 0xc8, 0x7b, 0x51, 0x85, 0x14, 0x0a, 0xc9, 0x3e, 0x0c, 0x59, 0x92, 0xa0, 0x52, 0x5a,
	0xce, 0x50, 0x78, 0x3f, 0x21, 0x14, 0xfd, 0xd3, 0x87, 0xcd, 0x37, 0x32, 0x45, 0xb2, 0x0d, 0x5d,
	0x9e, 0x7a, 0x89, 0x2e, 0x4f, 0x09, 0x81, 0x4d, 0xc1, 0x2e, 0xd0, 0x7b, 0xb7, 0xbf, 0x8d, 0xe7,
	0x2a, 0x64, 0xef, 0x39, 0x88, 0xd7, 0xff, 0x7c, 0x45, 0xc7, 0x2e, 0xde, 0xea, 0x6c, 0x72, 0xcd,
	0xb9, 0xd2, 0x28, 0x0a, 0x59, 0x6a, 0xba, 0xb9, 0xdf, 0x39, 0xe8, 0xc5, 0x01, 0x42, 0x9e, 0xc1,
	0x83, 0x62, 0x7e, 0x9e, 0xf3, 0x64, 0x86, 0x57, 0xb4, 0x67, 0x95, 0x6b, 0xc0, 0x58, 0x46, 0x91,
	0x16, 0x92, 0x0b, 0x4d, 0xfb, 0xce, 0x72, 0x75, 0x6e, 0xb1, 0xb8, 0x75, 0x23, 0x8b, 0x83, 0x16,
	0x8b, 0xfb, 0x30, 0x34, 0x95, 0xa9, 0x98, 0x7c, 0xe0, 0xa8, 0x09, 0x20, 0x13, 0x17, 0x57, 0x05,
	0x8a, 0x94, 0x8b, 0x8c, 0xc2, 0x7e, 0xe7, 0x60, 0x10, 0xd7, 0x00, 0xd9, 0x83, 0x7e, 0x21, 0x95,
	0x9e, 0x17, 0x74, 0x68, 0x55, 0xfd, 0xc9, 0xfa, 0x94, 0x4a, 0xa7, 0x72, 0x29, 0xe8, 0x43, 0xef,
	0xd3, 0x9f, 0x8d, 0xc5, 0x19, 0x62, 0xc1, 0x72, 0xbe, 0x40, 0x3a, 0xb2, 0x44, 0xd4, 0x80, 0xc9,
	0x46, 0xb1, 0x05, 0x26, 0x52, 0x4c, 0x79, 0x46, 0xb7, 0xad, 0xc3, 0x00, 0x31, 0xda, 0xae, 0x72,
	0x86, 0xa7, 0x1d, 0xc7, 0xd3, 0x0a, 0xb0, 0xd1, 0x0a, 0x8d, 0xe5, 0x94, 0x25, 0x48, 0x77, 0xdd,
	0xed, 0x0a, 0x30, 0xd9, 0xe6, 0x4c, 0xe9, 0xe4, 0x2d, 0x26, 0x33, 0x2e, 0xe8, 0x23, 0x97, 0x6d,
	0x00, 0x91, 0x08, 0x1e, 0x9a, 0xe3, 0x85, 0x4c, 0xf9, 0x94, 0x63, 0x4a, 0x89, 0x15, 0x69, 0x60,
	0xe4, 0x00, 0x76, 0xbc, 0xb8, 0xb5, 0xbc, 0x60, 0x39, 0x7d, 0x6c, 0xb3, 0x68, 0xc3, 0xd6, 0x9a,
	0x4c, 0x58, 0x5e, 0xd5, 0xe6, 0x89, 0xb7, 0x16, 0x60, 0x26, 0x26, 0xc3, 0x4c, 0xf2, 0x96, 0x89,
	0x0c, 0x15, 0x7d, 0xea, 0x62, 0x0a, 0x20, 0xc3, 0x08, 0xcb, 0x73, 0xb9, 0xc4, 0x94, 0x17, 0x8a,
	0xee, 0xb9, 0xfa, 0xd6, 0x88, 0xe9, 0x47, 0xae, 0xac, 0x4d, 0xfa, 0x91, 0xa5, 0xab, 0x3a, 0x92,
	0xcf, 0x60, 0x97, 0x2b, 0x2e, 0x32, 0xe3, 0x28, 0x63, 0x1a, 0x97, 0xec, 0x8a, 0x3e, 0xb3, 0x22,
	0xd7, 0x70, 0x13, 0x07, 0x57, 0xe9, 0x9c, 0xe5, 0x4a, 0xb3, 0x64, 0x46, 0x3f, 0xb1, 0x62, 0x21,
	0x64, 0x6a, 0x9d, 0x0a, 0x25, 0xa7, 0x53, 0x4a, 0xed, 0xa5, 0x3f, 0xd9, 0xce, 0x36, 0xee, 0x4a,
	0x13, 0x2e, 0xfd, 0xd8, 0xc5, 0x57, 0x23, 0xd1, 0x9f, 0x5d, 0xd8, 0x39, 0x35, 0xcc, 0x7c, 0x5f,
	0x8f, 0x24, 0x85, 0x2d, 0x35, 0xb7, 0x55, 0xb3, 0xc3, 0x36, 0x88, 0xab, 0x23, 0x79, 0x01, 0xdb,
	0x02, 0x31, 0x2d, 0x10, 0xcb, 0x79, 0x91, 0x32, 0xed, 0x66, 0x6f, 0x10, 0xb7, 0x50, 0x93, 0x9b,
	0x41, 0x5c, 0x57, 0x78, 0xc9, 0x0d, 0x97, 0x5b, 0x1b, 0xaf, 0xba, 0xfc, 0x02, 0x95, 0x62, 0x19,
	0xda, 0xe1, 0xf3, 0x5d, 0xee, 0xa1, 0x66, 0x97, 0xf7, 0xda, 0x5d, 0xfe, 0x29, 0x8c, 0x8c, 0xcd,
	0x19, 0x5e, 0x79, 0x47, 0x7d, 0x2b, 0xd1, 0x04, 0x0d, 0x0f, 0x06, 0x48, 0x31, 0x47, 0x8d, 0x76,
	0x0e, 0x07, 0x71, 0x80, 0x44, 0x7f, 0x77, 0x61, 0xf4, 0x33, 0x62, 0xa9, 0x56, 0x2c, 0x1c, 0xc0,
	0x0e, 0x57, 0xd8, 0x28, 0x8f, 0x63, 0xa3, 0x0d, 0x93, 0x23, 0x20, 0x0d, 0xc0, 0x71, 0xed, 0xb6,
	0xd2, 0x9a, 0x9b, 0x7b, 0x6c, 0x93, 0xbb, 0x6d, 0xb7, 0xc1, 0x07, 0x6e, 0xb7, 0xf6, 0x24, 0x6c,
	0xad, 0x99, 0x84, 0x1b, 0xf7, 0x42, 0xf4, 0x6f, 0x07, 0x76, 0xbf, 0x7b, 0xa7, 0x9b, 0x04, 0xfe,
	0xff, 0xd2, 0xfc, 0xa3, 0x0b, 0xfd, 0xd3, 0x9c, 0xa3, 0xdb, 0xeb, 0x45, 0xc9, 0x17, 0x4c, 0xa3,
	0xc9, 0xce, 0x7f, 0x1d, 0x6b, 0xa4, 0x99, 0x7c, 0xb7, 0x9d, 0x7c, 0x63, 0x4f, 0x6e, 0xb4, 0xf7,
	0x64, 0x90, 0xfe, 0xe6, 0xfb, 0xd3, 0xef, 0xb5, 0xd2, 0x7f, 0x01, 0xdb, 0x0a, 0xcb, 0x05, 0x96,
	0x2d, 0x5a, 0x5b, 0xa8, 0xdd, 0xe1, 0x16, 0xb1, 0x34, 0xf9, 0x2f, 0x52, 0x8d, 0x98, 0xd8, 0xdc,
	0xc9, 0xc4, 0xe6, 0x38, 0xae, 0x81, 0x68, 0x02, 0xa3, 0xd3, 0x12, 0x99, 0x46, 0xf3, 0x45, 0x8e,
	0xf1, 0x92, 0x3c, 0x07, 0xfb, 0x7c, 0xb0, 0x14, 0x0c, 0x4f, 0xe0, 0xc8, 0xbe, 0x2b, 0xec, 0xa5,
	0x7b, 0x56, 0xb4, 0x14, 0xd4, 0x5d, 0x14, 0x7e, 0xb3, 0x33, 0xfb, 0x01, 0x1e, 0x42, 0x85, 0xdb,
	0x3d, 0x9c, 0xc1, 0x30, 0x46, 0x96, 0xd6, 0xf6, 0x6f, 0x7e, 0xe8, 0x04, 0x8f, 0x99, 0x6e, 0xf3,
	0x31, 0x73, 0x18, 0x1a, 0xba, 0xdd, 0xef, 0x2f, 0x30, 0x7a, 0x6d, 0xb7, 0xcd, 0x5d, 0x3d, 0x9b,
	0xd5, 0xe8, 0x5c, 0xbd, 0xa9, 0xdf, 0x39, 0x21, 0x14, 0xbd, 0x6c, 0x9a, 0x54, 0xef, 0xdf, 0xdd,
	0x26, 0xeb, 0x33, 0xac, 0x46, 0xf4, 0x3e, 0x59, 0xff, 0x00, 0xdb, 0x67, 0xa8, 0xeb, 0x71, 0xbf,
	0x8f, 0xad, 0xaf, 0xc2, 0xa0, 0x14, 0x79, 0x09, 0x3d, 0xf3, 0x15, 0x51, 0x9e, 0xc2, 0xc7, 0x8e,
	0xc2, 0xc6, 0x5a, 0x89, 0x9d, 0x44, 0xf4, 0xba, 0x15, 0x85, 0x22, 0x27, 0x30, 0xc0, 0x77, 0x3a,
	0xd4, 0xdf, 0x73, 0xfa, 0xed, 0xcd, 0x14, 0xaf, 0xe4, 0xa2, 0xcf, 0x01, 0x56, 0x5f, 0xbf, 0xdb,
	0x3b, 0xed, 0xa7, 0x40, 0x5a, 0x91, 0x6f, 0x56, 0x4f, 0x8d, 0xd2, 0x1b, 0xf6, 0x8a, 0x4f, 0x9d,
	0x62, 0xeb, 0xb3, 0x1a, 0xb7, 0xa5, 0x4f, 0xfe, 0xda, 0x80, 0xa1, 0xb1, 0xfe, 0x2b, 0x96, 0x0b,
	0x9e, 0x20, 0x39, 0x86, 0x9e, 0x7d, 0x1b, 0x13, 0xe2, 0x0c, 0x84, 0xcf, 0xf1, 0xf1, 0xe3, 0x06,
	0xe6, 0x57, 0xec, 0x2b, 0x80, 0x7a, 0xb8, 0x88, 0x17, 0x69, 0xcc, 0xe7, 0x78, 0x0d, 0xa8, 0xc8,
	0x31, 0x0c, 0xaa, 0xc6, 0x25, 0x8f, 0x9c, 0x40, 0x30, 0x11, 0xe3, 0x6b, 0x90, 0x32, 0x9e, 0xea,
	0x21, 0xab, 0x3c, 0x35, 0xe6, 0x74, 0xbc, 0x06, 0xb4, 0x7a, 0x75, 0x83, 0x56, 0x7a, 0x8d, 0x29,
	0x18, 0xaf, 0x01, 0x6d, 0x31, 0xab, 0xc6, 0xa8, 0x22, 0x0c, 0xba, 0x77, 0x7c, 0x0d, 0x52, 0xc7,
	0x1d, 0xf2, 0xb5, 0x6d, 0xa6, 0xaa, 0xda, 0xe4, 0xc9, 0x4a, 0x26, 0xe8, 0xd5, 0xf1, 0x3a, 0xd4,
	0x28, 0x1f, 0xc2, 0x96, 0x2f, 0x18, 0xd9, 0x6d, 0xd5, 0xef, 0x72, 0xdc, 0x46, 0xd4, 0xb7, 0x93,
	0xdf, 0x0f, 0x33, 0x29, 0xb3, 0x1c, 0x8f, 0x32, 0x99, 0x33, 0x91, 0x1d, 0xc9, 0x32, 0x9b, 0xd8,
	0xbf, 0x53, 0xe7, 0xf3, 0xe9, 0x44, 0x5f, 0x15, 0xa8, 0x26, 0x33, 0x21, 0x97, 0xc2, 0xfe, 0xd1,
	0x2a, 0xce, 0xcf, 0xfb, 0xf6, 0xf2, 0xcb, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x11, 0xa6, 0x77,
	0x7c, 0x7e, 0x0d, 0x00, 0x00,
}
