version: "3.4"

services:
  coredns:
    image: coredns/coredns
    command: -conf /root/dnsconfig/Corefile
    container_name: coredns
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - /root/netmaker/config/dnsconfig:/root/dnsconfig
