server:
    corednsaddr: 147.182.251.203 # Address of CoreDNS Server (set locally with resolvectl)
    grpcaddress: 10.101.0.1:50051 # Address of GRPC Server (used for all interaction with server after registration)
    apiaddress: 1.2.3.4:8081 # Address of API Server (used only for registration/unregistration)
    accesskey: 5qKTbTgsvb45y3qyRmWft # Key used to sign up with server. Used only during registration
node:
    name: my-computer # name of this node
    interface: nm-example # name of interface to create/use for WG
    network: example # name of network this ode is a part of
    password: $2a$0afehuytviN/thMpVlCYkonxy.Ws2.rNCJjBSAa3HZuhrK5hpYxme # encrypted node password, used to retrieve JWT. Can be changed to new pass in plaintext and CLI will update/replace with encrypted pass
    macaddress: 6c:4b:91:0g:68:7b # MAC of node. Used as a Unique ID
    localaddress: 192.168.1.32 # Address on local network, used as endpoint for other local nodes for faster comms
    wgaddress: 10.7.11.2 # Private WG addres on network
    wgaddress6: "f8:34:41:77:5c:15" # Private ipv6 address if network is dual stack
    roaming: "yes" # Whether or not to grab new endpoint value automatically
    dnson: "no" # Whether or not to set local DNS based on Netmaker's Private DNS server
    islocal: "no" # Based on network. If yes, will use local IP as endpoint.
    isdualstack: "yes" # Use IPv6 in addition to IPv4
    isingressgateway: "no" # whether or not node is an ingress gateway (will set iptables forwarding rules)
    allowedips: "" # additional IP's to add to client
    localrange: "" # local range if it's a local network. For instance, 192.168.1.0/24
    postup: "" # postup command, used by ingress/egress gateways to set iptables
    postdown: "" # postdown command, used by ingress/egress gateways to set iptables
    port: 51821 # WG port to use
    keepalive: 20 # default keepalive with nodes
    publickey: 8/q9cOg7c9QjnoXygVrY/VNE197VMRadJodkb1ZsujA= # public key of node to show to other nodes
    privatekey: "" # private key, set only for changing and then will revert to blank in config
    endpoint: 78.170.22.168 # public endpoint for reaching node 
    postchanges: "false" # if true, will post and config file changes on next checkin and then revert to false
    ipforwarding: "yes" # set ip forwarding; highly recommended to leave on
    isstatic: "no" # if yes, daemon will not change pubkey, endpoint, or address
    udpholepunch: "yes" # run UDP hole punching (will ignore port above, e.g. 51821)
    network: home # the network (duplicate of node.network)
daemon: "yes" # whether or not to manage systemd
operatingsystem: "" # not currently in use