// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: grpc/siem/siem.proto

package siem

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SIEMService_InitSIEM_FullMethodName      = "/netmaker.siem.SIEMService/InitSIEM"
	SIEMService_TerminateSIEM_FullMethodName = "/netmaker.siem.SIEMService/TerminateSIEM"
)

// SIEMServiceClient is the client API for SIEMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Unary RPCs called by the netmaker server to control SIEM export
// on the netmaker exporter.
type SIEMServiceClient interface {
	// Instruct the exporter to start forwarding events to the given SIEM provider.
	InitSIEM(ctx context.Context, in *InitSIEMRequest, opts ...grpc.CallOption) (*SIEMResponse, error)
	// Instruct the exporter to stop all SIEM forwarding.
	TerminateSIEM(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SIEMResponse, error)
}

type sIEMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSIEMServiceClient(cc grpc.ClientConnInterface) SIEMServiceClient {
	return &sIEMServiceClient{cc}
}

func (c *sIEMServiceClient) InitSIEM(ctx context.Context, in *InitSIEMRequest, opts ...grpc.CallOption) (*SIEMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SIEMResponse)
	err := c.cc.Invoke(ctx, SIEMService_InitSIEM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sIEMServiceClient) TerminateSIEM(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SIEMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SIEMResponse)
	err := c.cc.Invoke(ctx, SIEMService_TerminateSIEM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SIEMServiceServer is the server API for SIEMService service.
// All implementations must embed UnimplementedSIEMServiceServer
// for forward compatibility.
//
// *
// Unary RPCs called by the netmaker server to control SIEM export
// on the netmaker exporter.
type SIEMServiceServer interface {
	// Instruct the exporter to start forwarding events to the given SIEM provider.
	InitSIEM(context.Context, *InitSIEMRequest) (*SIEMResponse, error)
	// Instruct the exporter to stop all SIEM forwarding.
	TerminateSIEM(context.Context, *emptypb.Empty) (*SIEMResponse, error)
	mustEmbedUnimplementedSIEMServiceServer()
}

// UnimplementedSIEMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSIEMServiceServer struct{}

func (UnimplementedSIEMServiceServer) InitSIEM(context.Context, *InitSIEMRequest) (*SIEMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitSIEM not implemented")
}
func (UnimplementedSIEMServiceServer) TerminateSIEM(context.Context, *emptypb.Empty) (*SIEMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateSIEM not implemented")
}
func (UnimplementedSIEMServiceServer) mustEmbedUnimplementedSIEMServiceServer() {}
func (UnimplementedSIEMServiceServer) testEmbeddedByValue()                     {}

// UnsafeSIEMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SIEMServiceServer will
// result in compilation errors.
type UnsafeSIEMServiceServer interface {
	mustEmbedUnimplementedSIEMServiceServer()
}

func RegisterSIEMServiceServer(s grpc.ServiceRegistrar, srv SIEMServiceServer) {
	// If the following call panics, it indicates UnimplementedSIEMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SIEMService_ServiceDesc, srv)
}

func _SIEMService_InitSIEM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitSIEMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SIEMServiceServer).InitSIEM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SIEMService_InitSIEM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SIEMServiceServer).InitSIEM(ctx, req.(*InitSIEMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SIEMService_TerminateSIEM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SIEMServiceServer).TerminateSIEM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SIEMService_TerminateSIEM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SIEMServiceServer).TerminateSIEM(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SIEMService_ServiceDesc is the grpc.ServiceDesc for SIEMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SIEMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmaker.siem.SIEMService",
	HandlerType: (*SIEMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitSIEM",
			Handler:    _SIEMService_InitSIEM_Handler,
		},
		{
			MethodName: "TerminateSIEM",
			Handler:    _SIEMService_TerminateSIEM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/siem/siem.proto",
}
