// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: grpc/auditlogs/auditlogs.proto

package auditlogs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Audit log event generated by the netmaker server.
// Mirrors the schema.Event struct.
type AuditLogEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Action performed (e.g. "CREATE", "UPDATE", "DELETE") — maps to schema.Action
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Who initiated the action (maps to schema.Origin: "DASHBOARD", "API", "NMCTL", "CLIENT-APP")
	Origin string `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	// User or entity that triggered the action
	TriggeredBy string `protobuf:"bytes,4,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	// Network the event is scoped to (empty for global events)
	NetworkId string `protobuf:"bytes,5,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Structured JSON blobs — map to datatypes.JSON fields in schema.Event
	Source *structpb.Struct `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Target *structpb.Struct `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	Diff   *structpb.Struct `protobuf:"bytes,8,opt,name=diff,proto3" json:"diff,omitempty"`
	// Timestamp (milliseconds since Unix epoch)
	TsMs          int64 `protobuf:"varint,9,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEvent) Reset() {
	*x = AuditLogEvent{}
	mi := &file_grpc_auditlogs_auditlogs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEvent) ProtoMessage() {}

func (x *AuditLogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auditlogs_auditlogs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEvent.ProtoReflect.Descriptor instead.
func (*AuditLogEvent) Descriptor() ([]byte, []int) {
	return file_grpc_auditlogs_auditlogs_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLogEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLogEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogEvent) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *AuditLogEvent) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

func (x *AuditLogEvent) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *AuditLogEvent) GetSource() *structpb.Struct {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *AuditLogEvent) GetTarget() *structpb.Struct {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AuditLogEvent) GetDiff() *structpb.Struct {
	if x != nil {
		return x.Diff
	}
	return nil
}

func (x *AuditLogEvent) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

// *
// Envelope sent by the netmaker server containing multiple AuditLogEvents.
type AuditLogEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditLogEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogEnvelope) Reset() {
	*x = AuditLogEnvelope{}
	mi := &file_grpc_auditlogs_auditlogs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogEnvelope) ProtoMessage() {}

func (x *AuditLogEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auditlogs_auditlogs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogEnvelope.ProtoReflect.Descriptor instead.
func (*AuditLogEnvelope) Descriptor() ([]byte, []int) {
	return file_grpc_auditlogs_auditlogs_proto_rawDescGZIP(), []int{1}
}

func (x *AuditLogEnvelope) GetEvents() []*AuditLogEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// *
// Response from the exporter acknowledging receipt of a batch.
type AuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogResponse) Reset() {
	*x = AuditLogResponse{}
	mi := &file_grpc_auditlogs_auditlogs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogResponse) ProtoMessage() {}

func (x *AuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auditlogs_auditlogs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogResponse.ProtoReflect.Descriptor instead.
func (*AuditLogResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auditlogs_auditlogs_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuditLogResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_grpc_auditlogs_auditlogs_proto protoreflect.FileDescriptor

const file_grpc_auditlogs_auditlogs_proto_rawDesc = "" +
	"\n" +
	"\x1egrpc/auditlogs/auditlogs.proto\x12\x12netmaker.auditlogs\x1a\x1cgoogle/protobuf/struct.proto\"\xb5\x02\n" +
	"\rAuditLogEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12!\n" +
	"\ftriggered_by\x18\x04 \x01(\tR\vtriggeredBy\x12\x1d\n" +
	"\n" +
	"network_id\x18\x05 \x01(\tR\tnetworkId\x12/\n" +
	"\x06source\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06source\x12/\n" +
	"\x06target\x18\a \x01(\v2\x17.google.protobuf.StructR\x06target\x12+\n" +
	"\x04diff\x18\b \x01(\v2\x17.google.protobuf.StructR\x04diff\x12\x13\n" +
	"\x05ts_ms\x18\t \x01(\x03R\x04tsMs\"M\n" +
	"\x10AuditLogEnvelope\x129\n" +
	"\x06events\x18\x01 \x03(\v2!.netmaker.auditlogs.AuditLogEventR\x06events\"B\n" +
	"\x10AuditLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2t\n" +
	"\x0fAuditLogService\x12a\n" +
	"\x0fStreamAuditLogs\x12$.netmaker.auditlogs.AuditLogEnvelope\x1a$.netmaker.auditlogs.AuditLogResponse(\x010\x01B,Z*github.com/gravitl/netmaker/grpc/auditlogsb\x06proto3"

var (
	file_grpc_auditlogs_auditlogs_proto_rawDescOnce sync.Once
	file_grpc_auditlogs_auditlogs_proto_rawDescData []byte
)

func file_grpc_auditlogs_auditlogs_proto_rawDescGZIP() []byte {
	file_grpc_auditlogs_auditlogs_proto_rawDescOnce.Do(func() {
		file_grpc_auditlogs_auditlogs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auditlogs_auditlogs_proto_rawDesc), len(file_grpc_auditlogs_auditlogs_proto_rawDesc)))
	})
	return file_grpc_auditlogs_auditlogs_proto_rawDescData
}

var file_grpc_auditlogs_auditlogs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_auditlogs_auditlogs_proto_goTypes = []any{
	(*AuditLogEvent)(nil),    // 0: netmaker.auditlogs.AuditLogEvent
	(*AuditLogEnvelope)(nil), // 1: netmaker.auditlogs.AuditLogEnvelope
	(*AuditLogResponse)(nil), // 2: netmaker.auditlogs.AuditLogResponse
	(*structpb.Struct)(nil),  // 3: google.protobuf.Struct
}
var file_grpc_auditlogs_auditlogs_proto_depIdxs = []int32{
	3, // 0: netmaker.auditlogs.AuditLogEvent.source:type_name -> google.protobuf.Struct
	3, // 1: netmaker.auditlogs.AuditLogEvent.target:type_name -> google.protobuf.Struct
	3, // 2: netmaker.auditlogs.AuditLogEvent.diff:type_name -> google.protobuf.Struct
	0, // 3: netmaker.auditlogs.AuditLogEnvelope.events:type_name -> netmaker.auditlogs.AuditLogEvent
	1, // 4: netmaker.auditlogs.AuditLogService.StreamAuditLogs:input_type -> netmaker.auditlogs.AuditLogEnvelope
	2, // 5: netmaker.auditlogs.AuditLogService.StreamAuditLogs:output_type -> netmaker.auditlogs.AuditLogResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpc_auditlogs_auditlogs_proto_init() }
func file_grpc_auditlogs_auditlogs_proto_init() {
	if File_grpc_auditlogs_auditlogs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auditlogs_auditlogs_proto_rawDesc), len(file_grpc_auditlogs_auditlogs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auditlogs_auditlogs_proto_goTypes,
		DependencyIndexes: file_grpc_auditlogs_auditlogs_proto_depIdxs,
		MessageInfos:      file_grpc_auditlogs_auditlogs_proto_msgTypes,
	}.Build()
	File_grpc_auditlogs_auditlogs_proto = out.File
	file_grpc_auditlogs_auditlogs_proto_goTypes = nil
	file_grpc_auditlogs_auditlogs_proto_depIdxs = nil
}
