// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: grpc/auditlogs/auditlogs.proto

package auditlogs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditLogService_StreamAuditLogs_FullMethodName = "/netmaker.auditlogs.AuditLogService/StreamAuditLogs"
)

// AuditLogServiceClient is the client API for AuditLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// Bidirectional streaming:
//   - Netmaker server continuously sends AuditLogEnvelope batches.
//   - Exporter replies with AuditLogResponse ACKs.
type AuditLogServiceClient interface {
	StreamAuditLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuditLogEnvelope, AuditLogResponse], error)
}

type auditLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditLogServiceClient(cc grpc.ClientConnInterface) AuditLogServiceClient {
	return &auditLogServiceClient{cc}
}

func (c *auditLogServiceClient) StreamAuditLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AuditLogEnvelope, AuditLogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuditLogService_ServiceDesc.Streams[0], AuditLogService_StreamAuditLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuditLogEnvelope, AuditLogResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditLogService_StreamAuditLogsClient = grpc.BidiStreamingClient[AuditLogEnvelope, AuditLogResponse]

// AuditLogServiceServer is the server API for AuditLogService service.
// All implementations must embed UnimplementedAuditLogServiceServer
// for forward compatibility.
//
// *
// Bidirectional streaming:
//   - Netmaker server continuously sends AuditLogEnvelope batches.
//   - Exporter replies with AuditLogResponse ACKs.
type AuditLogServiceServer interface {
	StreamAuditLogs(grpc.BidiStreamingServer[AuditLogEnvelope, AuditLogResponse]) error
	mustEmbedUnimplementedAuditLogServiceServer()
}

// UnimplementedAuditLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditLogServiceServer struct{}

func (UnimplementedAuditLogServiceServer) StreamAuditLogs(grpc.BidiStreamingServer[AuditLogEnvelope, AuditLogResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamAuditLogs not implemented")
}
func (UnimplementedAuditLogServiceServer) mustEmbedUnimplementedAuditLogServiceServer() {}
func (UnimplementedAuditLogServiceServer) testEmbeddedByValue()                         {}

// UnsafeAuditLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditLogServiceServer will
// result in compilation errors.
type UnsafeAuditLogServiceServer interface {
	mustEmbedUnimplementedAuditLogServiceServer()
}

func RegisterAuditLogServiceServer(s grpc.ServiceRegistrar, srv AuditLogServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditLogService_ServiceDesc, srv)
}

func _AuditLogService_StreamAuditLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AuditLogServiceServer).StreamAuditLogs(&grpc.GenericServerStream[AuditLogEnvelope, AuditLogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditLogService_StreamAuditLogsServer = grpc.BidiStreamingServer[AuditLogEnvelope, AuditLogResponse]

// AuditLogService_ServiceDesc is the grpc.ServiceDesc for AuditLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netmaker.auditlogs.AuditLogService",
	HandlerType: (*AuditLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAuditLogs",
			Handler:       _AuditLogService_StreamAuditLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/auditlogs/auditlogs.proto",
}
