name: Generate Documentation

on: 
  push:
    branches:
      - 'master'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: gravitl/netmaker
          ref: master

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generating Docs
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          swag init --md docs/ --outputTypes yaml

      - name: Update Repo
        run: 
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          if ! git diff --exit-code; then
              git add docs/
              git commit -am "GH Action Files added $(date)"
              git push -f origin main
          fi