name: Publish Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker tag'
        required: true
  pull_request:
    branches:
      - 'test'
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        run: |
            if [[ -n "${{ github.event.inputs.tag }}" ]]; then
              TAG=${{ github.event.inputs.tag }}
            elif [[ "${{ github.base_ref }}" == 'master' ]]; then
              TAG="latest"
            else
              TAG="${{ github.base_ref }}"
            fi
            echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - if: github.event_name != 'pull_request'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: coredns/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: gravitl/netmaker-coredns:${{ env.TAG }}
