# creates a PR from release branch to master
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "netmaker version"
        required: true
jobs:
  pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: create pr
        run: |
          curl -X POST -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'\
          -H 'X-GitHub-Api-Version: 2022-11-28'  https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{"title":"{{ github.event.inputs.version }}","head":"release_${{ github.event.inputs.version }}","base":"master"}'


